import type { ScanResult } from '@/types/scanner'
import jsPDF from 'jspdf'

export class PdfGenerator {
    generate(result: ScanResult): jsPDF {
        const doc = new jsPDF()
        const pageWidth = doc.internal.pageSize.getWidth()
        const pageHeight = doc.internal.pageSize.getHeight()
        const margin = 20
        let yPosition = margin

        // Helper function to add text with auto page break
        const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
            doc.setFontSize(fontSize)
            doc.setFont('helvetica', isBold ? 'bold' : 'normal')

            const lines = doc.splitTextToSize(text, pageWidth - 2 * margin)

            for (const line of lines) {
                if (yPosition > pageHeight - margin) {
                    doc.addPage()
                    yPosition = margin
                }
                doc.text(line, margin, yPosition)
                yPosition += fontSize * 0.5
            }

            yPosition += 5
        }

        // Title
        doc.setFillColor(59, 130, 246)
        doc.rect(0, 0, pageWidth, 40, 'F')
        doc.setTextColor(255, 255, 255)
        doc.setFontSize(24)
        doc.setFont('helvetica', 'bold')
        doc.text('Security Scan Report', margin, 25)

        yPosition = 50
        doc.setTextColor(0, 0, 0)

        // Basic Info
        addText(`URL: ${result.url}`, 10, true)
        addText(`Scan Date: ${new Date(result.timestamp).toLocaleString()}`, 10)
        addText(``, 10) // Spacer

        // Score Box
        const scoreColor = this.getScoreColor(result.score)
        doc.setFillColor(...scoreColor)
        doc.roundedRect(margin, yPosition, 60, 30, 3, 3, 'F')
        doc.setTextColor(255, 255, 255)
        doc.setFontSize(18)
        doc.setFont('helvetica', 'bold')
        doc.text(`Score: ${result.score}`, margin + 5, yPosition + 15)
        doc.setFontSize(10)
        doc.text(`Risk: ${result.riskLevel}`, margin + 5, yPosition + 25)
        doc.setTextColor(0, 0, 0)

        yPosition += 40

        // Summary
        addText('Summary', 14, true)
        addText(`Total Checks: ${result.summary.totalChecks}`, 10)
        addText(`Passed: ${result.summary.passedChecks}`, 10)
        addText(`Failed: ${result.summary.failedChecks}`, 10)
        addText('', 10) // Spacer

        // Findings
        addText('Detailed Findings', 14, true)

        if (result.findings.length === 0) {
            addText('✓ No security issues detected. Great job!', 10)
        } else {
            result.findings.forEach((finding, index) => {
                // Add page break before finding if needed
                if (yPosition > pageHeight - 60) {
                    doc.addPage()
                    yPosition = margin
                }

                // Finding header
                const severityColor = this.getSeverityColor(finding.severity)
                doc.setFillColor(...severityColor)
                doc.roundedRect(margin, yPosition, pageWidth - 2 * margin, 8, 2, 2, 'F')
                doc.setTextColor(255, 255, 255)
                doc.setFontSize(11)
                doc.setFont('helvetica', 'bold')
                doc.text(`${index + 1}. ${finding.title}`, margin + 2, yPosition + 5)
                doc.setTextColor(0, 0, 0)
                yPosition += 12

                // Finding details
                addText(`Module: ${finding.module}`, 9)
                addText(`Severity: ${finding.severity} (Impact: -${finding.scoreImpact} points)`, 9)
                addText(`Description: ${finding.description}`, 9)
                addText(`Recommendation: ${finding.recommendation}`, 9)
                addText('', 9) // Spacer
            })
        }

        // Footer - Disclaimer
        doc.addPage()
        yPosition = margin
        addText('Disclaimer', 14, true)
        addText(
            'This tool performs lightweight automated checks and does not replace a professional security audit. ' +
            'The results should be used as a starting point for improving security posture. ' +
            'For production systems, always consult with qualified security professionals and conduct thorough penetration testing.',
            10
        )

        // Footer text
        doc.setFontSize(8)
        doc.setTextColor(128, 128, 128)
        doc.text('Generated by Vibecode Security Scanner', pageWidth / 2, pageHeight - 10, { align: 'center' })

        return doc
    }

    private getScoreColor(score: number): [number, number, number] {
        if (score >= 75) return [34, 197, 94] // green
        if (score >= 60) return [234, 179, 8] // yellow
        return [239, 68, 68] // red
    }

    private getSeverityColor(severity: string): [number, number, number] {
        switch (severity) {
            case 'CRITICAL': return [127, 29, 29] // dark red
            case 'HIGH': return [239, 68, 68] // red
            case 'MEDIUM': return [234, 179, 8] // yellow
            case 'LOW': return [59, 130, 246] // blue
            default: return [107, 114, 128] // gray
        }
    }
}
